from turtle import *

v = Turtle()
screen = Screen()
screen.bgcolor('black')
v.speed(1)
v.pensize(5)
screen.title("tg1 logo")
screen.cv._rootwindow.resizable(False, False)
color = 'cyan'
scale = 20
v.color(color)
v.penup()
v.goto((-10*scale,-5*scale))
v.pendown()

v.begin_fill()
v.fillcolor(color)

v.forward(15*scale)
v.left(90)
v.forward(5*scale)
v.left(90)
v.forward(3*scale)
v.left(90)
v.forward(2*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(6*scale)
v.left(90)
v.forward(3*scale)
v.left(90)
v.forward(9*scale)
v.left(90)
v.forward(6*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(2*scale)
v.left(90)
v.forward(3*scale)
v.left(90)
v.forward(2*scale)
v.right(90)
v.forward(3*scale)
v.left(90)
v.forward(3*scale)
v.left(90)
v.forward(12*scale)

v.end_fill()

v.penup()
v.left(90)
v.forward(18*scale)
v.pendown()

v.begin_fill()
v.fillcolor(color)

v.left(90)
v.forward(6*scale)
v.left(90)
v.forward(2*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(5*scale)
v.right(90)
v.forward(12*scale)
v.right(90)
v.forward(3*scale)
v.right(90)
v.forward(3*scale)

v.end_fill()

v.hideturtle()

screen.mainloop()